### ISSUE TITLE
Configure snowpack to locate web_module relatively

### ISSUE THREAD

**Issue by snsinfu** [snsinfu/3dpile#1]
I want to put the page and modules under https://snsinfu.github.io/3dpile/, but the scripts built by snowpack import threejs from `/web_modules/three.js` and the browser gets 404 Not Found. I manually edit view.js to make it import modules from relative paths, which seems to work. Investigate the correct way to make snowpack to do this.

**Comment by lkwilson** [comment]
Here is a work around. You have to manually specify the base directory, which in your case is /3dpile.
https://github.com/snowpackjs/snowpack/discussions/1423#discussioncomment-117314

**Comment by snsinfu** [comment]
The issue seems to be fixed in recent snowpack releases. I updated snowpack from 2.6.4 to 2.18.4, and now `snowpack build` produces relative imports for web_module by default. So, my import issue is solved.

Anyway, thanks for the info!
